---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  labels:
    env: prod
spec:
  containers:
  - name: kubectl
    image: zerthimon/kubectl:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
